### ISSUE TITLE
Error while running test_transcend.py

### ISSUE THREAD

**Issue by shivaang12** [DavideBuffelli/TrASenD#1]
I did pre-processing just as mentioned in the readme files. After I run the test_transcend.py file, I am getting the following error after the buffer is filled.

```
2021-04-05 01:07:44.902258: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:97] Filling up shuffle buffer (this may take a while): 51062 of 53460
2021-04-05 01:07:54.900188: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:97] Filling up shuffle buffer (this may take a while): 52400 of 53460
2021-04-05 01:08:04.901125: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:97] Filling up shuffle buffer (this may take a while): 53195 of 53460
2021-04-05 01:08:06.643283: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:135] Shuffle buffer filled.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expect 6006 fields but have 2412 in record 0
	 [[Node: DecodeCSV = DecodeCSV[OUT_TYPE=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], field_delim=",", na_value="", select_cols=[], use_quote_delim=true, _device="/device:CPU:0"](arg0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0, DecodeCSV/record_defaults_0,.....
```

it goes on and on. I think the problem is in the input to the database object. It would be great if you could help me.

Thanks!

P.S
After some debugging, this is what the input received by function `read_csv`
`Tensor("arg0:0", shape=(), dtype=string, device=/device:CPU:0)`
this clearly suggest that there must be something wrong with the input.

**Comment by DavideBuffelli** [comment]
Hi, I will need to look into this a bit more. It seems like you could run the preprocessing correctly, but you have problems when training and testing the model.

It could be that you need to set the parameters correctly (lines 16 to 23; the parameters that change between datasets are `num_sensors` and `num_output_classes`) for the dataset you are interested in (the ones you find now should be for HHAR). Which dataset are you interested in?

If you think the problem is the preprocessing step, then you could also try using the code from the DeepSense authors:
https://github.com/yscacaca/HHAR-Data-Process

or you could directly download the already preprocessed dataset (assuming you are interested in the HHAR dataset):
https://github.com/yscacaca/DeepSense

**Comment by shivaang12** [comment]
Thanks for your reply.

I was previously using PAMAP2 but I also tried HHAR dataset and I am getting same error. I don't know what is your environment setup. I am using Docker image of tensorflow 1.10 with py3 and gpu. If you are running through docker could you please share your docker image?

**Comment by DavideBuffelli** [comment]
Sorry, I'm not using Docker. 

When using PAMAP2 remember to set `num_sensors` to 9, and `num_output_classes` to 24.

Could you try using the already preprocessed HHAR data from https://github.com/yscacaca/DeepSense ?

**Comment by shivaang12** [comment]
Sorry for not being clear. I tried preprocessed HHAR dataset too but I am getting same error.

**Comment by DavideBuffelli** [comment]
Sorry for the late reply. Unfortunately at the moment I don't have access to a GPU, and on a CPU I have not been able to reproduce your error. I have cloned the repo and launched the code on the preprocessed HHAR data from https://github.com/yscacaca/DeepSense and it works fine (on a CPU). Did you make any changes to the code? And does it run if you launch it on CPU?

**Comment by shivaang12** [comment]
I tried running on CPU it is giving me same error. Thank you for the reply. I will close the issue as I am not perusing this code anymore.  I find it very hard to debug tensorflow. 
Again thank you for your help.
